version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: investments
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql_data:
